using System.Collections.Generic;

namespace CasesApi.Models
{
    public class Incident
    {
        public string Name { get; set; } // primary key, autogenerated, string
        public string Description { get; set; }

        public ICollection<Account> Accounts { get; set; }
    }
}
